config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sneakers#index'

  resources :sneakers do
    member do
      # /sneakers/16/charge (much like /sneakers/16/edit)
      post 'charge'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord

    def price_in_dollars
        price.to_f / 100.0
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :edit, :update, :destroy, :charge]

  before_action :authenticate_user!, only: [:charge]
  
  # GET /sneakers
  # GET /sneakers.json
  def index
    @sneakers = Sneaker.all
  end

  # GET /sneakers/1
  # GET /sneakers/1.json
  def show
  end

  # GET /sneakers/new
  def new
    @sneaker = Sneaker.new
  end

  # GET /sneakers/1/edit
  def edit
  end

  # POST /sneakers/1/charge
  def charge

    if current_user.stripe_id.blank?
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
      current_user.stripe_id = customer.id
      current_user.save!
    end

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @sneaker.price.to_i,
        description: @sneaker.description,
        currency: 'AUD'
      )

      # current_user.charges << Charge.new(charge_id: charge.id)
      flash[:notice] = 'Payment made!'
      redirect_back fallback_location: sneakers_path      


      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_back fallback_location: sneakers_path

      rescue ActiveRecord::RecordNotSaved => e
        flash[:error] = e.message
        redirect_back fallback_location: sneakers_path

  end

  # POST /sneakers
  # POST /sneakers.json
  def create
    @sneaker = Sneaker.new(sneaker_params)

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully created.' }
        format.json { render :show, status: :created, location: @sneaker }
      else
        format.html { render :new }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sneakers/1
  # PATCH/PUT /sneakers/1.json
  def update
    respond_to do |format|
      if @sneaker.update(sneaker_params)
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @sneaker }
      else
        format.html { render :edit }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1
  # DELETE /sneakers/1.json
  def destroy
    @sneaker.destroy
    respond_to do |format|
      format.html { redirect_to sneakers_url, notice: 'Sneaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sneaker
      @sneaker = Sneaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sneaker_params
      params.require(:sneaker).permit(:name, :description, :price)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakersPgStripe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://checkout.stripe.com/v3/checkout/button.css' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sneakers/_charge_form.html.erb
<%= form_tag charge_sneaker_path(sneaker) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <!--
    <label class="amount">
      <span>Amount: $<%= number_to_currency sneaker.price_in_dollars %></span>
    </label>
    -->

  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-email='tim.moon7@gmail.com'
          data-name='<%= sneaker.name %>'
          data-currency='AUD'
          data-amount=<%= sneaker.price %>
          data-locale="auto"></script>
<% end %>

app/views/sneakers/_form.html.erb
<%= form_with(model: sneaker, local: true) do |form| %>
  <% if sneaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h2>

      <ul>
      <% sneaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sneaker_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :sneaker_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :sneaker_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sneakers/edit.html.erb
<h1>Editing Sneaker</h1>

<%= render 'form', sneaker: @sneaker %>

<%= link_to 'Show', @sneaker %> |
<%= link_to 'Back', sneakers_path %>

app/views/sneakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sneakers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sneakers.each do |sneaker| %>
      <tr>
        <td><%= sneaker.name %></td>
        <td><%= sneaker.description %></td>
        <td><%= sneaker.price_in_dollars  %></td>
        <td><%= link_to 'Show', sneaker %></td>
        <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
        <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sneaker', new_sneaker_path %>

app/views/sneakers/new.html.erb
<h1>New Sneaker</h1>

<%= render 'form', sneaker: @sneaker %>

<%= link_to 'Back', sneakers_path %>

app/views/sneakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sneaker.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sneaker.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @sneaker.price_in_dollars %>
</p>

<% if user_signed_in? %>
  <%= render 'charge_form', sneaker: @sneaker, user: current_user %>
<% else %>
    <%= link_to new_user_registration_path, class: 'stripe-button-el' do %>
     <span style="display: block; min-height: 30px;">Pay with Card</span>
  <% end %>
<% end %>

<br>
<%= link_to 'Edit', edit_sneaker_path(@sneaker) %> |
<%= link_to 'Back', sneakers_path %>